### ISSUE TITLE
why python backend?

### ISSUE THREAD

**Issue by mxlsr** [effectiveaccelerationism/text-to-banger#15]
Got fully working node js server/client with streaming:
https://github.com/mxlsr/real-banger-tweets-api

**Comment by codethazine** [comment]
Since the project is eventually going to have its own model, it's better to maintain the API server running in Python for better integration with current modeling standards. Also, as things stand, it shouldn't even be necessary to make a request to an internal API server redirecting to OAI, we could just go directly to the OAI API from the frontend, but it's good to have the Python integration already up and running for future support
